services:
  db:
    container_name: nextcloud_db
    image: mariadb:lts
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_USER=$MARIADB_USER

  app:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - $HOME/nextcloud:/data
      - ./config:/config
      - $EXTERNAL_DIR:$EXTERNAL_DIR
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=linuxserver/mods:nextcloud-notify-push

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server

  imaginary:
    restart: unless-stopped
    image: nextcloud/aio-imaginary:latest
    container_name: nextcloud_imaginary
    environment:
       PORT: 11000
    command: -enable-url-source -cors
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    cap_add:
      - SYS_NICE
