services:
  collabora:
    image: collabora/code:latest
    privileged: true
    container_name: collabora
    environment:
      - "extra_params=--o:remote_font_config.url=$CLOUD/apps/richdocuments/settings/fonts.json --o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=160.202.39.[0-9]{1,3} --o:net.post_allow_host[1]=100.64.0.[0-9]{1,3} --o:per_document.max_concurrency=12 --o:num_prespawn_children=12"
      - "aliasgroup1=$CLOUD:443"
      - "domain1=$CLOUD:443"
      - DONT_GEN_SSL_CERT=true
      - "server_name=$HOST"
    restart: unless-stopped
    networks: 
      - nginx_proxy
    cap_add:
      - MKNOD

networks:
  nginx_proxy:
    external: true
