services:
  collabora:
    image: collabora/code:latest
    privileged: true
    container_name: collabora
    environment:
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=160.202.39.[0-9]{1,3}"
      - "aliasgroup1=cloud.coolans.dev"
      - 'domain=cloud.coolans.dev'
      - DONT_GEN_SSL_CERT=false
    restart: unless-stopped
    networks: 
      - nginx_proxy
    cap_add:
      - MKNOD

networks:
  nginx_proxy:
    external: true
