services:
  imaginary:
    restart: unless-stopped
    image: nextcloud/aio-imaginary:latest
    container_name: imaginary
    environment:
       PORT: 11000
    command: -enable-url-source -cors
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "100.64.0.2:11000:11000"
    cap_add:
      - SYS_NICE
