services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    command: serve
    restart: unless-stopped
    volumes:
        - ./config:/etc/headscale/
        - ./data:/var/lib/headscale/
        - ./run:/var/run/headscale/
    networks: 
        - nginx_proxy

    ports:
        - "3478:3478/udp"
networks:
  nginx_proxy:
    external: true
