# my docker compose for all arrs
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr:/config
      - $DATA:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - starr

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr:/config
      - $DATA:/data
    networks:
      - starr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bazarr:/config
      - $DATA/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - starr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - starr

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - transmission:/config
      - $DATA/downloads:/downloads
      - $DATA/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - starr

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=192.168.1.2
    volumes:
      - jellyfin:/config
      - $DATA/media:/data
    ports:
      - 8096:8096
      - 7359:7359/udp # optional
      - 1900:1900/udp # optional
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    restart: unless-stopped
    networks:
      - starr

volumes:
  bazarr:
  prowlarr:
  radarr:
  transmission:
  sonarr:
  jellyfin:
    name: jellyfin_jellyfin

networks:
  starr:
    name: starr
