services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "100.64.0.2:8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
